### ISSUE TITLE
Do you mind/can you say which file has this `Permission denied` on the trackback?

### ISSUE THREAD

**Issue by evandrocoan** [WoLpH/portalocker#41]
```
Traceback (most recent call last):
  File "f:\python\lib\site-packages\portalocker\portalocker.py", line 58, in unlock
    msvcrt.locking(file_.fileno(), constants.LOCK_UN, 0x7fffffff)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\lib\logging\__init__.py", line 1940, in shutdown
    h.close()
  File "F:\SublimeText\Data\Packages\concurrentloghandler\all\concurrent_log_handler\__init__.py", line 320, in close
    unlock(self.stream_lock)
  File "f:\python\lib\site-packages\portalocker\portalocker.py", line 61, in unlock
    exceptions.LockException.LOCK_FAILED, exc_value.strerror)
portalocker.exceptions.LockException: (1, 'Permission denied')
```

Do you mind/can you say which file has this `Permission denied` on the trackback?

Because I do not know which one it is.

**Comment by WoLpH** [comment]
I've added a file handle (`fh`) attribute to the `LockException` so you can find out. Note that it depends on the file handle which properties it has.
