### ISSUE TITLE
LockException(OSError(22, 'Invalid argument')) when using NON_BLOCKING flag on Linux

### ISSUE THREAD

**Issue by elibroftw** [WoLpH/portalocker#77]
OS: Zorin OS (Ubuntu based Linux)

## Example

```py
import portalocker
from portalocker.exceptions import LockException

file = open('test.lock', 'w+', encoding='utf-8')
portalocker.lock(file, portalocker.LockFlags.NON_BLOCKING)
```

## Traceback

```py
Traceback (most recent call last):
  File "/home/maste/.local/lib/python3.10/site-packages/portalocker/portalocker.py", line 138, in lock
    fcntl.flock(file_.fileno(), flags)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maste/Documents/GitHub/music-caster/src/test.py", line 5, in <module>
    portalocker.lock(file, portalocker.LockFlags.NON_BLOCKING)
  File "/home/maste/.local/lib/python3.10/site-packages/portalocker/portalocker.py", line 142, in lock
    raise exceptions.LockException(exc_value, fh=file_)
portalocker.exceptions.LockException: [Errno 22] Invalid argument
```

**Comment by elibroftw** [comment]
Solution: I had to use `portalocker.lock(file, portalocker.LockFlags.EXCLUSIVE | portalocker.LockFlags.NON_BLOCKING)`
I'm not forced to do this on Windows.

**Comment by WoLpH** [comment]
Thank you for letting me know :)

I've added a clear warning for these cases. Generally I wouldn't recommend using the low-level locking system at all. Using the `Lock` object is easier and handles these types of quirks for you:

```
import portalocker
with portalocker.Lock('somefile', timeout=1) as fh:
    ...
```
